replicaCount: 1

image:
  repository: ramanijadala/todo-app
  tag: latest      # Replace with correct tag or use --set
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
